package edu.uark.mobileprogramming.findfamiliar.Enum

enum class Skills {
    ACROBATICS, ANIMAL_HANDLING, ARCANA, DECEPTION, HISTORY,
    INSIGHT, INTIMIDATION, INVESTIGATION, MEDICINE, NATURE,
    PERCEPTION, PERFORMANCE, PERSUASION, RELIGION, SLEIGHT_OF_HAND,
    STEALTH, SURVIVAL
}